// ═══════════════════════════════════════════
// BODY TEMPLATES — v1 (12×16) and v2 (32×48) character art strings
// 8 preset characters per version
//
// v2 Anatomy map (32×48):
// Row  0-13  HEAD: hair(0-5), forehead(6-7), eyes(8-9), nose(10-11), mouth(12-13)
// Row 14-32  TORSO: neck(14-15), shoulders(16-17), chest(18-24), waist(25-28), hips(29-32)
// Row 33-47  LEGS: thighs(33-37), knees(38-39), calves(40-43), feet(44-47)
// ═══════════════════════════════════════════

import type { BodyId } from '../types';
import { normalizeArt } from '../parser';

// ─── V1 Templates (12×16) ────────────────────────────────────

/** V1 art strings per body ID (12×16 pixel art). */
export const BODY_TEMPLATES_V1: Record<BodyId, string> = {
  aria:  '....HHHH....\n...HHHHHH...\n..HHHhHHHH..\n.HHSSSSSSHH.\n.HSEESSEESH.\n.HSEwSSEwSH.\n.HSrSSSSrSH.\n..HSSmmSSH..\n...HSSSSH...\n...TTTTTT...\n..TTTTTTTT..\n.ATTTTTTTTA.\n.ATTTttTTTA.\n..TTTTTTTT..\n...PP..PP...\n..FFF..FFF..',
  kofi:  '..HHHHHHHH..\n..HHHHHHHH..\n...HHHHHH...\n..HSSSSSSH..\n..SEESSEES..\n..SEwSSEwS..\n..SrSSSSrS..\n...SSmmSS...\n....SSSS....\n...TTTTTT...\n..TTTTTTTT..\n.ATTTTTTTTA.\n.ATTTttTTTA.\n..TTTTTTTT..\n...PP..PP...\n..FFF..FFF..',
  mei:   '...HHHHHH...\n..HHHHHHHH..\n.HhhhhhhhhH.\n.HHSSSSSSHH.\n.HSEESSEESH.\n.HSEwSSEwSH.\n..HrSSSSrH..\n...SSmmSS...\n....SSSS....\n...TTTTTT...\n..TTTTTTTT..\n.ATTTTTTTTA.\n.ATTTttTTTA.\n..TTTTTTTT..\n...PP..PP...\n..FFF..FFF..',
  diego: '..H.HHhH.H..\n..HHHHHHHH..\n..HHHhHHHH..\n..HSSSSSSH..\n..SEESSEES..\n..SEwSSEwS..\n..SrSSSSrS..\n...SSmmSS...\n....SSSS....\n...TTTTTT...\n..TTTTTTTT..\n.ATTTTTTTTA.\n.ATTTttTTTA.\n..TTTTTTTT..\n...PP..PP...\n..FFF..FFF..',
  zara:  '..HHH..HHH..\n.HHHH..HHHH.\n..HHHHHHHH..\n..HSSSSSSH..\n..SEESSEES..\n..SEwSSEwS..\n..SrSSSSrS..\n...SSmmSS...\n....SSSS....\n...TTTTTT...\n..TTTTTTTT..\n.ATTTTTTTTA.\n.ATTTttTTTA.\n..TTTTTTTT..\n...PP..PP...\n..FFF..FFF..',
  alex:  '..HHHH......\n..HHHHHHH...\n..HHHhHHHH..\n..HSSSSSSH..\n..SEESSEES..\n..SEwSSEwS..\n..SrSSSSrS..\n...SSmmSS...\n....SSSS....\n...TTTTTT...\n..TTTTTTTT..\n.ATTTTTTTTA.\n.ATTTttTTTA.\n..TTTTTTTT..\n...PP..PP...\n..FFF..FFF..',
  priya: '....HHHH....\n...HHHHHH...\n..HHHhHHHH..\n.HHSSSSSSHH.\n.HSEESSEESH.\n.HSEwSSEwSH.\n..SrSSSSrSH.\n...SSmmSS.H.\n....SSSS.H..\n...TTTTTT...\n..TTTTTTTT..\n.ATTTTTTTTA.\n.ATTTttTTTA.\n..TTTTTTTT..\n...PP..PP...\n..FFF..FFF..',
  liam:  '.H..HHHH..H.\n.HHHHHHHHHH.\n..HHHhHHHH..\n..HSSSSSSH..\n..SEESSEES..\n..SEwSSEwS..\n..SrSSSSrS..\n...SSmmSS...\n....SSSS....\n...TTTTTT...\n..TTTTTTTT..\n.ATTTTTTTTA.\n.ATTTttTTTA.\n..TTTTTTTT..\n...PP..PP...\n..FFF..FFF..',
};

/** V1 palettes per body ID (12-key, no digit aliases). */
export const DEFAULT_PALETTES_V1: Record<BodyId, Record<string, string>> = {
  aria:  { H: '#E8C35A', h: '#FFD980', S: '#FFDAB9', E: '#2A2040', w: '#FFFFFF', r: '#FFB5A0', m: '#E8907A', T: '#9D7AFF', t: '#7B5FCC', A: '#FFDAB9', P: '#6B4FBB', F: '#5A3FAA' },
  kofi:  { H: '#1A1008', h: '#2A1A10', S: '#8B5E3C', E: '#0A0A1E', w: '#FFFFFF', r: '#7A4E2C', m: '#6A3E20', T: '#2A9D8F', t: '#1A7A6A', A: '#8B5E3C', P: '#155A50', F: '#104A40' },
  mei:   { H: '#1A1A2E', h: '#2A2A40', S: '#DEB887', E: '#1A1020', w: '#FFFFFF', r: '#D4A06A', m: '#C08060', T: '#E879F9', t: '#C060D0', A: '#DEB887', P: '#9040A0', F: '#7030A0' },
  diego: { H: '#5C3A1E', h: '#7A5030', S: '#D4A574', E: '#1A1020', w: '#FFFFFF', r: '#C89058', m: '#B07848', T: '#3B82F6', t: '#2A60C0', A: '#D4A574', P: '#1A3070', F: '#102060' },
  zara:  { H: '#1A1008', h: '#2A1A10', S: '#7B4B2A', E: '#0A0A1E', w: '#FFFFFF', r: '#6A3B1A', m: '#5A3018', T: '#FF6B8A', t: '#D04A6A', A: '#7B4B2A', P: '#8A2040', F: '#701838' },
  alex:  { H: '#6B48A8', h: '#9D7AFF', S: '#D2A37C', E: '#1A1020', w: '#FFFFFF', r: '#C0905A', m: '#A87848', T: '#4ECDC4', t: '#3AABA0', A: '#D2A37C', P: '#1A6A60', F: '#105A50' },
  priya: { H: '#1A1008', h: '#2A1810', S: '#C68642', E: '#0A0A1E', w: '#FFFFFF', r: '#B87530', m: '#A06828', T: '#FFD166', t: '#E0B040', A: '#C68642', P: '#8A6A10', F: '#705808' },
  liam:  { H: '#CC4422', h: '#E85830', S: '#FFE0C0', E: '#1A2030', w: '#FFFFFF', r: '#FFBBA0', m: '#E8907A', T: '#818CF8', t: '#6060D0', A: '#FFE0C0', P: '#3A3080', F: '#2A2070' },
};

// ─── V2 Templates (32×48) ────────────────────────────────────

/**
 * Full-body v2 art string templates per body ID.
 * These are the "master" art strings with palette-key chars.
 * Palette is applied at render time via parseArt().
 */
export const BODY_TEMPLATES_V2: Record<BodyId, string> = {
  // ────────────────────────────────────
  // ARIA — Slim body, long straight blonde hair
  // ────────────────────────────────────
  aria: normalizeArt([
    '..............HHHH..............',
    '.............HHHHHH.............',
    '............H1HHH1HH............',
    '...........HHHHHHHHHH...........',
    '..........HHHHhHhHHHHH..........',
    '.........HH1HHhHhHH1HHH.........',
    '.........HHSS3SSSS3SSHH.........',
    '.........HHSSSSSSSSSSSHH.........',
    '.........HS54ESSSS54ESHH.........',
    '.........HSSSSSSSSSSSSSH.........',
    '..........HSSS3SS3SSSH..........',
    '..........HSSSSSSSSSHH..........',
    '..........HSSSSmmSSSSH..........',
    '...........HSSSSSSSHH...........',
    '............SS2SSSS2............',
    '............SSSSSSSS............',
    '...........2SSSSSSSS2...........',
    '..........SSTTTTTTTTSS..........',
    '..........STTTTTTTTTTS..........',
    '.........9T77TTTTTT77T9.........',
    '.........9TTTTTTTTTTTT9.........',
    '.........STTTTTTTTTTTS.........',
    '..........TTTTTTTTTTTT..........',
    '..........T6TTTTTTTT6T..........',
    '..........TTTTTTTTTTTT..........',
    '...........TTTTTTTTTT...........',
    '...........T6TTTTTT6T...........',
    '............TTTTTTTT............',
    '............T6TTTT6T............',
    '............PPPPPPPP............',
    '...........PP8PPPP8PP...........',
    '...........PPPPPPPPPP...........',
    '...........PP8PPPP8PP...........',
    '...........PP....PP.PP..........',
    '...........PP....PPPP...........',
    '...........PP.....PP...........',
    '...........PP.....PP...........',
    '...........PP.....PP...........',
    '............P.....P............',
    '............P.....P............',
    '............P.....P............',
    '............P.....P............',
    '............P.....P............',
    '............P.....P............',
    '...........FF.....FF...........',
    '...........FFF...FFF...........',
    '..........0FFF...FFF0..........',
    '..........0FFF...FFF0..........',
  ]),

  // ────────────────────────────────────
  // KOFI — Athletic body, flat-top fade dark hair
  // ────────────────────────────────────
  kofi: normalizeArt([
    '..........OHHHHHHHHO..........',
    '..........OHHHHHHHHO..........',
    '..........OHHH1HHHHO..........',
    '...........HHHHHHHH............',
    '..........HHHHHHHHHHH..........',
    '..........HhHHHHHHhHH..........',
    '..........HSSSSSSSSSSH..........',
    '..........HSSSSSSSSSH..........',
    '..........S54ESSSS54ES..........',
    '..........SSSSSSSSSSSS..........',
    '...........SSS3SS3SSS...........',
    '...........SSSSSSSSSS...........',
    '...........SSSSmmSSSS...........',
    '............SSSSSSSS............',
    '.............S2SS2S.............',
    '.............SSSSSS.............',
    '............2SSSSSS2............',
    '...........SSSSSSSSSS...........',
    '.........9STTTTTTTTTS9..........',
    '........9STTTTTTTTTTTS9.........',
    '........9T77TTTTTTTT7T9.........',
    '........STTTTTTTTTTTTTS.........',
    '.........TTTTTTTTTTTTTT.........',
    '.........T6TTTTTTTTTT6T.........',
    '..........TTTTTTTTTTTT..........',
    '..........TTTTTTTTTTTT..........',
    '..........T6TTTTTTT6T...........',
    '...........TTTTTTTTTT...........',
    '...........T6TTTTTT6T...........',
    '...........PPPPPPPPPP...........',
    '..........PP8PPPPPP8PP..........',
    '..........PPPPPPPPPPPP..........',
    '..........PP8PPPPPP8PP..........',
    '..........PP....PP..PP..........',
    '..........PPP...PPPP............',
    '..........PP.....PPP............',
    '..........PP......PP...........',
    '..........PP......PP...........',
    '...........P......P............',
    '...........P......P............',
    '...........P......P............',
    '...........P......P............',
    '...........P......P............',
    '...........P......P............',
    '..........FFF....FFF...........',
    '..........FFF....FFF...........',
    '.........0FFFF..FFFF0..........',
    '.........0FFFF..FFFF0..........',
  ]),

  // ────────────────────────────────────
  // MEI — Slim body, bob with bangs, dark hair
  // ────────────────────────────────────
  mei: normalizeArt([
    '.............HHHHHH.............',
    '............HHHHHHHH............',
    '...........HHH1HH1HHH...........',
    '..........HhhhhhhhhhHH..........',
    '..........HhHHhHhHHhHH..........',
    '.........HHhHHHHHHHhHHH.........',
    '.........HHSS3SSSS3SSHH.........',
    '.........HHSSSSSSSSSSSHH.........',
    '.........HS54ESSSS54ESHH.........',
    '.........HSSSSSSSSSSSSH.........',
    '..........HSSS3SS3SSSH..........',
    '..........HSSSSSSSSSHH..........',
    '..........HSSSrmmrSSH...........',
    '...........HSSSSSSSHH...........',
    '............SS2SS2SS............',
    '............SSSSSSSS............',
    '...........2SSSSSSSS2...........',
    '..........SSTTTTTTTTSS..........',
    '..........STTTTTTTTTTS..........',
    '.........9T77TTTTTT77T9.........',
    '.........9TTTTTTTTTTTT9.........',
    '.........STTTTTTTTTTTS.........',
    '..........TTTTTTTTTTTT..........',
    '..........T6TTTTTTTT6T..........',
    '..........TTTTTTTTTTTT..........',
    '...........TTTTTTTTTT...........',
    '...........T6TTTTTT6T...........',
    '............TTTTTTTT............',
    '............T6TTTT6T............',
    '............PPPPPPPP............',
    '...........PP8PPPP8PP...........',
    '...........PPPPPPPPPP...........',
    '...........PP8PPPP8PP...........',
    '...........PP....PP.PP..........',
    '...........PP....PPPP...........',
    '...........PP.....PP...........',
    '...........PP.....PP...........',
    '...........PP.....PP...........',
    '............P.....P............',
    '............P.....P............',
    '............P.....P............',
    '............P.....P............',
    '............P.....P............',
    '............P.....P............',
    '...........FF.....FF...........',
    '...........FFF...FFF...........',
    '..........0FFF...FFF0..........',
    '..........0FFF...FFF0..........',
  ]),

  // ────────────────────────────────────
  // DIEGO — Sturdy body, wavy brown hair
  // ────────────────────────────────────
  diego: normalizeArt([
    '...........H.HHHH.H............',
    '..........HHHHHHHHHHH...........',
    '..........HH1HhHhH1HH..........',
    '.........HHHHHhHhHHHHH.........',
    '.........HHHHHHHHHHHHH..........',
    '........HHhHHHHHHHHhHH.........',
    '........HHSSS3SSSS3SSSHH........',
    '........HHSSSSSSSSSSSSHH........',
    '........HS54ESSSSS54ESHH........',
    '........HSSSSSSSSSSSSSSH........',
    '.........HSSSS3SS3SSSSH.........',
    '.........HSSSSSSSSSSSSH.........',
    '.........HSSSSrmmrSSSH..........',
    '..........HSSSSSSSSSH...........',
    '...........SS2SSSS2S............',
    '...........SSSSSSSSSS...........',
    '..........2SSSSSSSSSS2..........',
    '.........SSSSSSSSSSSSSS.........',
    '........9SSTTTTTTTTTSS9.........',
    '........9STTTTTTTTTTTS9.........',
    '.......9ST77TTTTTTTT77TS9.......',
    '.......9STTTTTTTTTTTTTS9........',
    '........STTTTTTTTTTTTTTS........',
    '........T6TTTTTTTTTTTT6T........',
    '........TTTTTTTTTTTTTTT.........',
    '.........TTTTTTTTTTTTTT.........',
    '.........T6TTTTTTTTTT6T.........',
    '..........TTTTTTTTTTTT..........',
    '..........T6TTTTTTT6T...........',
    '..........PPPPPPPPPPPP..........',
    '.........PP8PPPPPPPP8PP.........',
    '.........PPPPPPPPPPPPPP.........',
    '.........PP8PPPPPPPP8PP.........',
    '.........PPP.....PP.PPP.........',
    '.........PPP.....PPPPP..........',
    '.........PP.......PPP...........',
    '.........PP.......PP...........',
    '.........PP.......PP...........',
    '..........P.......P............',
    '..........P.......P............',
    '..........P.......P............',
    '..........P.......P............',
    '..........P.......P............',
    '..........P.......P............',
    '.........FFF.....FFF...........',
    '.........FFFF...FFFF...........',
    '........0FFFF...FFFF0..........',
    '........0FFFF...FFFF0..........',
  ]),

  // ────────────────────────────────────
  // ZARA — Sturdy body, afro puffs
  // ────────────────────────────────────
  zara: normalizeArt([
    '.........HHH......HHH.........',
    '........H1HHH....HHH1H.........',
    '........HHHHH....HHHHH.........',
    '........HHHHHHHHHHHHHHH.........',
    '.........HHHHHHHHHHHHHH.........',
    '........HhHHHHHHHHHHhHH........',
    '........HHSSS3SSSS3SSSHH........',
    '........HHSSSSSSSSSSSSHH........',
    '........HS54ESSSSS54ESHH........',
    '........HSSSSSSSSSSSSSSH........',
    '.........HSSSS3SS3SSSSH.........',
    '.........HSSSSSSSSSSSSH.........',
    '.........HSSSSSmmSSSSH..........',
    '..........HSSSSSSSSSH...........',
    '...........SS2SSSS2S............',
    '...........SSSSSSSSSS...........',
    '..........2SSSSSSSSSS2..........',
    '.........SSSSSSSSSSSSSS.........',
    '........9SSTTTTTTTTTSS9.........',
    '........9STTTTTTTTTTTS9.........',
    '.......9ST77TTTTTTTT77TS9.......',
    '.......9STTTTTTTTTTTTTS9........',
    '........STTTTTTTTTTTTTTS........',
    '........T6TTTTTTTTTTTT6T........',
    '........TTTTTTTTTTTTTTT.........',
    '.........TTTTTTTTTTTTTT.........',
    '.........T6TTTTTTTTTT6T.........',
    '..........TTTTTTTTTTTT..........',
    '..........T6TTTTTTT6T...........',
    '..........PPPPPPPPPPPP..........',
    '.........PP8PPPPPPPP8PP.........',
    '.........PPPPPPPPPPPPPP.........',
    '.........PP8PPPPPPPP8PP.........',
    '.........PPP.....PP.PPP.........',
    '.........PPP.....PPPPP..........',
    '.........PP.......PPP...........',
    '.........PP.......PP...........',
    '.........PP.......PP...........',
    '..........P.......P............',
    '..........P.......P............',
    '..........P.......P............',
    '..........P.......P............',
    '..........P.......P............',
    '..........P.......P............',
    '.........FFF.....FFF...........',
    '.........FFFF...FFFF...........',
    '........0FFFF...FFFF0..........',
    '........0FFFF...FFFF0..........',
  ]),

  // ────────────────────────────────────
  // ALEX — Athletic body, undercut purple hair
  // ────────────────────────────────────
  alex: normalizeArt([
    '..........HHHH.................',
    '..........HHHHHHHH.............',
    '..........HH1HhH1HHH...........',
    '..........HHHHhHHHHHH..........',
    '..........HHHHHHHHHHH..........',
    '..........HhHHHHHHhHH..........',
    '..........HSSSSSSSSSSH..........',
    '..........HSSSSSSSSSH..........',
    '..........S54ESSSS54ES..........',
    '..........SSSSSSSSSSSS..........',
    '...........SSS3SS3SSS...........',
    '...........SSSSSSSSSS...........',
    '...........SSSSmmSSSS...........',
    '............SSSSSSSS............',
    '.............S2SS2S.............',
    '.............SSSSSS.............',
    '............2SSSSSS2............',
    '...........SSSSSSSSSS...........',
    '.........9STTTTTTTTTS9..........',
    '........9STTTTTTTTTTTS9.........',
    '........9T77TTTTTTTT7T9.........',
    '........STTTTTTTTTTTTTS.........',
    '.........TTTTTTTTTTTTTT.........',
    '.........T6TTTTTTTTTT6T.........',
    '..........TTTTTTTTTTTT..........',
    '..........TTTTTTTTTTTT..........',
    '..........T6TTTTTTT6T...........',
    '...........TTTTTTTTTT...........',
    '...........T6TTTTTT6T...........',
    '...........PPPPPPPPPP...........',
    '..........PP8PPPPPP8PP..........',
    '..........PPPPPPPPPPPP..........',
    '..........PP8PPPPPP8PP..........',
    '..........PP....PP..PP..........',
    '..........PPP...PPPP............',
    '..........PP.....PPP............',
    '..........PP......PP...........',
    '..........PP......PP...........',
    '...........P......P............',
    '...........P......P............',
    '...........P......P............',
    '...........P......P............',
    '...........P......P............',
    '...........P......P............',
    '..........FFF....FFF...........',
    '..........FFF....FFF...........',
    '.........0FFFF..FFFF0..........',
    '.........0FFFF..FFFF0..........',
  ]),

  // ────────────────────────────────────
  // PRIYA — Petite body, long braid, brown skin
  // ────────────────────────────────────
  priya: normalizeArt([
    '..............HHHH..............',
    '.............HHHHHH.............',
    '............HH1HH1HH............',
    '...........HHHHHHHHHH...........',
    '...........HHHhHhHHHH...........',
    '..........HH1HHHHHHhHH..........',
    '..........HHSS3SSS3SSHH.........',
    '..........HHSSSSSSSSSSHH.........',
    '..........HS54ESSS54ESHH.........',
    '..........HSSSSSSSSSSSH..........',
    '...........HSSS3S3SSSH...........',
    '...........HSSSSSSSSHh..........',
    '...........HSSSrmmrSH.h.........',
    '............HSSSSSH..h..........',
    '.............SS2S2S..h..........',
    '.............SSSSSS..h..........',
    '............2SSSSS2.h...........',
    '...........SSTTTTTTHS...........',
    '...........STTTTTTTTSH..........',
    '..........9T7TTTTTT7TS..........',
    '..........9TTTTTTTTTT9..........',
    '..........STTTTTTTTTS...........',
    '...........TTTTTTTTTTH..........',
    '...........T6TTTTTT6T...........',
    '...........TTTTTTTTTT...........',
    '............TTTTTTTT............',
    '............T6TTTT6T............',
    '.............TTTTTT.............',
    '.............T6TT6T.............',
    '.............PPPPPP.............',
    '............PP8PP8PP............',
    '............PPPPPPPP............',
    '............PP8PP8PP............',
    '............PP...PP.PP..........',
    '............PP...PPPP...........',
    '............PP....PP............',
    '............PP....PP............',
    '............PP....PP............',
    '.............P....P.............',
    '.............P....P.............',
    '.............P....P.............',
    '.............P....P.............',
    '............FF....FF............',
    '............FFF..FFF............',
    '...........0FFF..FFF0...........',
    '................................',
    '................................',
    '................................',
  ]),

  // ────────────────────────────────────
  // LIAM — Athletic body, messy auburn hair
  // ────────────────────────────────────
  liam: normalizeArt([
    '..........H..HHHH..H...........',
    '..........HHHHHHHHHH............',
    '..........HH1HhH1HHH...........',
    '..........HHHHHHHHHHH..........',
    '.........H1HHHHHHHH1HH..........',
    '..........HhHHHHHHhHH..........',
    '..........HSSSSSSSSSSH..........',
    '..........HSSSSSSSSSH..........',
    '..........S54ESSSS54ES..........',
    '..........SSSSSSSSSSSS..........',
    '...........SSS3SS3SSS...........',
    '...........SSSSSSSSSS...........',
    '...........SSSSmmSSSS...........',
    '............SSSSSSSS............',
    '.............S2SS2S.............',
    '.............SSSSSS.............',
    '............2SSSSSS2............',
    '...........SSSSSSSSSS...........',
    '.........9STTTTTTTTTS9..........',
    '........9STTTTTTTTTTTS9.........',
    '........9T77TTTTTTTT7T9.........',
    '........STTTTTTTTTTTTTS.........',
    '.........TTTTTTTTTTTTTT.........',
    '.........T6TTTTTTTTTT6T.........',
    '..........TTTTTTTTTTTT..........',
    '..........TTTTTTTTTTTT..........',
    '..........T6TTTTTTT6T...........',
    '...........TTTTTTTTTT...........',
    '...........T6TTTTTT6T...........',
    '...........PPPPPPPPPP...........',
    '..........PP8PPPPPP8PP..........',
    '..........PPPPPPPPPPPP..........',
    '..........PP8PPPPPP8PP..........',
    '..........PP....PP..PP..........',
    '..........PPP...PPPP............',
    '..........PP.....PPP............',
    '..........PP......PP...........',
    '..........PP......PP...........',
    '...........P......P............',
    '...........P......P............',
    '...........P......P............',
    '...........P......P............',
    '...........P......P............',
    '...........P......P............',
    '..........FFF....FFF...........',
    '..........FFF....FFF...........',
    '.........0FFFF..FFFF0..........',
    '.........0FFFF..FFFF0..........',
  ]),
};

/**
 * Default palettes per body ID (matching the original character designs).
 * Used when rendering preset characters (no customization).
 */
export const DEFAULT_PALETTES_V2: Record<BodyId, Record<string, string>> = {
  aria: {
    H: '#E8C35A', h: '#C9A530', '1': '#F2D880',
    S: '#FFDAB9', '2': '#D9B89D', '3': '#FFE8D0',
    E: '#2A6090', '4': '#0A0A12', '5': '#F0F0F5',
    w: '#FFFFFF', r: '#FFB5A0', m: '#E8907A',
    T: '#9D7AFF', t: '#7B5FCC', '6': '#7B5FCC', '7': '#B99AFF',
    A: '#FFDAB9', '9': '#C9A590',
    P: '#6B4FBB', '8': '#5A3FAA',
    F: '#5A3FAA', '0': '#4A2F9A',
    O: '#1A1020',
  },
  kofi: {
    H: '#1A1008', h: '#0E0804', '1': '#2A1A10',
    S: '#8B5E3C', '2': '#764F32', '3': '#A07048',
    E: '#1A1420', '4': '#0A0A12', '5': '#F0F0F5',
    w: '#FFFFFF', r: '#7A4E2C', m: '#6A3E20',
    T: '#2A9D8F', t: '#1A7A6A', '6': '#1A7A6A', '7': '#40B5A5',
    A: '#8B5E3C', '9': '#6A4828',
    P: '#155A50', '8': '#104A40',
    F: '#104A40', '0': '#083A30',
    O: '#1A1020',
  },
  mei: {
    H: '#1A1A2E', h: '#121220', '1': '#2A2A42',
    S: '#DEB887', '2': '#BDA070', '3': '#F0CCA0',
    E: '#1A1020', '4': '#0A0A12', '5': '#F0F0F5',
    w: '#FFFFFF', r: '#D4A06A', m: '#C08060',
    T: '#E879F9', t: '#C060D0', '6': '#C060D0', '7': '#F09AFF',
    A: '#DEB887', '9': '#B89870',
    P: '#9040A0', '8': '#7830A0',
    F: '#7030A0', '0': '#602090',
    O: '#1A1020',
  },
  diego: {
    H: '#5C3A1E', h: '#4A2E16', '1': '#7A5030',
    S: '#D4A574', '2': '#B88C60', '3': '#E8BA88',
    E: '#1A1020', '4': '#0A0A12', '5': '#F0F0F5',
    w: '#FFFFFF', r: '#C89058', m: '#B07848',
    T: '#3B82F6', t: '#2A60C0', '6': '#2A60C0', '7': '#5A9AFF',
    A: '#D4A574', '9': '#A88058',
    P: '#1A3070', '8': '#102060',
    F: '#102060', '0': '#081850',
    O: '#1A1020',
  },
  zara: {
    H: '#1A1008', h: '#0E0804', '1': '#2A1A10',
    S: '#7B4B2A', '2': '#663E22', '3': '#905A38',
    E: '#1A1420', '4': '#0A0A12', '5': '#F0F0F5',
    w: '#FFFFFF', r: '#6A3B1A', m: '#5A3018',
    T: '#FF6B8A', t: '#D04A6A', '6': '#D04A6A', '7': '#FF8AA0',
    A: '#7B4B2A', '9': '#5A3820',
    P: '#8A2040', '8': '#701838',
    F: '#701838', '0': '#601030',
    O: '#1A1020',
  },
  alex: {
    H: '#6B48A8', h: '#553890', '1': '#9D7AFF',
    S: '#D2A37C', '2': '#B88A66', '3': '#E8BA92',
    E: '#1A1020', '4': '#0A0A12', '5': '#F0F0F5',
    w: '#FFFFFF', r: '#C0905A', m: '#A87848',
    T: '#4ECDC4', t: '#3AABA0', '6': '#3AABA0', '7': '#70E0D8',
    A: '#D2A37C', '9': '#A88060',
    P: '#1A6A60', '8': '#105A50',
    F: '#105A50', '0': '#084A40',
    O: '#1A1020',
  },
  priya: {
    H: '#1A1008', h: '#0E0804', '1': '#2A1810',
    S: '#C68642', '2': '#A87038', '3': '#DA9A50',
    E: '#1A1420', '4': '#0A0A12', '5': '#F0F0F5',
    w: '#FFFFFF', r: '#B87530', m: '#A06828',
    T: '#FFD166', t: '#E0B040', '6': '#E0B040', '7': '#FFE088',
    A: '#C68642', '9': '#986430',
    P: '#8A6A10', '8': '#705808',
    F: '#705808', '0': '#584800',
    O: '#1A1020',
  },
  liam: {
    H: '#CC4422', h: '#AA3818', '1': '#E85830',
    S: '#FFE0C0', '2': '#D9C0A0', '3': '#FFF0D8',
    E: '#1A2030', '4': '#0A0A12', '5': '#F0F0F5',
    w: '#FFFFFF', r: '#FFBBA0', m: '#E8907A',
    T: '#818CF8', t: '#6060D0', '6': '#6060D0', '7': '#9AA0FF',
    A: '#FFE0C0', '9': '#D0B8A0',
    P: '#3A3080', '8': '#2A2070',
    F: '#2A2070', '0': '#1A1060',
    O: '#1A1020',
  },
};

/**
 * Get a preset character's art string and default palette.
 */
export function getPresetCharacter(bodyId: BodyId): { artString: string; palette: Record<string, string> } {
  return {
    artString: BODY_TEMPLATES_V2[bodyId],
    palette: DEFAULT_PALETTES_V2[bodyId],
  };
}
